services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DOMAIN=pkg.go.dev.local
      - SIGNATURE=Gopher 🇻🇳
      - THEME=atom-one-light